name: CI

on: push

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-18.04
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/surakshaaglave/SAP%20DevOps
            azure-pipeline-name: 'SAP DevOps-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }} 
    
name: Deploy

on: push

jobs:
     deploy:
        name: Call Azure Pipeline
        runs-on: ubuntu-18.04
        steps:
        - name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
          uses: Azure/pipelines@releases/v1
          with:
            azure-devops-project-url: 'https://dev.azure.com/surakshaaglave/SAP%20DevOps'
            azure-pipeline-name: 'New release pipeline'
            azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN_new }}'
